apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicas-3
  labels:
    name: replica-labels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: replica-service
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: NodePort