# apiVersion: v1
# kind: Pod
# metadata:
#   name: big-pod
#   namespace: payment-ns
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.25
#     resources:
#       requests:
#         cpu: "3"
#         memory: 2Gi
#       limits:
#         cpu: "3"
#         memory: 4Gi

apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  namespace: payment-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      requests:
        cpu: "500m"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: another-pod
  namespace: payment-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      requests:
        cpu: "1500m"  # ← This should work (500m used + 1500m = 2000m = 2 CPU quota)
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: tiny-pod
  namespace: payment-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      requests:
        cpu: "100m"  # ← Just 0.1 CPU
        memory: 512Mi
      limits:
        cpu: "200m"
        memory: 1Gi