# apiVersion: v1
# kind: Pod
# metadata:
#   name: big-pod
#   namespace: payment-ns
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.25
#     resources:
#       requests:
#         cpu: "3"
#         memory: 2Gi
#       limits:
#         cpu: "3"
#         memory: 4Gi

apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  namespace: payment-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      requests:
        cpu: "500m"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: another-pod
  namespace: payment-ns
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    resources:
      requests:
        cpu: "1500m"  # ← This should work (500m used + 1500m = 2000m = 2 CPU quota)
        memory: 2Gi
      limits:
        cpu: "2"
        memory: 4Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: payment-quota
  namespace: payment-ns
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"              # ← Max 10 pods total
    services: "5"           # ← Max 5 services
    persistentvolumeclaims: "3"  # ← Max 3 PVCs