apiVersion: v1
kind: Namespace
metadata: 
  name: payment-ns

---
apiVersion: v1 
kind: Namespace
metadata:
  name: order-ns
---
apiVersion: v1 
kind: Namespace
metadata: 
  name: delivery-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-ns