
apiVersion: v1
kind: Pod
metadata:
  name: broken-app
spec:
  initContainers:
  - name: setup
    image: busybox
    command: ['sh', '-c', 'echo Init 1; sleep 5']  
  containers:
  - name: app
    image: nginx

# kubectl apply -f broken-pod.yaml
# kubectl get pod broken-app